name: 'CURRENT WORLD EVENTS !!!'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4390845687594265
title: RETURN OF JESUS CHRIST ???
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a9311'
    - '#0e0307'
    - '#5edceb'
    - '#d0cd0e'
    - '#e26334'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.6859450018964708
purpose: []
