name: END TIMES
favicon: null
layout_spectrum: 0.5220370600000024
typography_spectrum: 0.4390845687594265
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6055743917822838
  lightness: 0.37305340683087707
  saturation: 0.20176457543857396
  rhythmicContrast: 0.6859450018964708
purpose: []
